#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if type dum > /dev/null
  then alias run=dum
  else alias run=pnpm
fi

# https://github.com/conventional-changelog/commitlint/issues/2742
run is-ci || run commitlint -g commitlint.config.cjs -e $1
